config/routes.rb
MiniRecruiting::Application.routes.draw do
  root :to => 'vacancies#index'
  
  resources :vacancies, only: :show do
    resources :job_applications, only: [:new, :create]
  end
  
  scope "/applicants/:applicant_id", as: "applicant" do
    resources :job_applications, only: [:edit, :update, :show]
  end
  

  devise_for :users, controllers: {sessions: "sessions"}
  devise_for :applicants, :controllers => {:registrations => "applicant_registrations"}
  devise_for :admin

  resources :job_assignments, only: [:new, :create]
  resources :users
  
  namespace :admin do
    resources :users
    resources :vacancies
    resources :job_applications
    resources :job_assignments, only: :show
    root :to => 'users#index'
    get "vacancies/:id/pdf" , to: "vacancies#new_pdf", as: "vacancy_pdf"
    post "vacancies/:id/g_pdf" , to: "vacancies#generate_pdf", as: "vacancy_g_pdf"
    resources :pdf_footer, only: [:edit, :update]
  end
  get "/guest/apply_for/:vacancy_id/new", to: "guest_apply#new", as: "guest_new"
  post "/guest/apply_for/:vacancy_id/", to: "guest_apply#create", as: "guest_create"
  get "vacancy/:id/pdf" , to: "vacancies#new_pdf", as: "vacancy_pdf"
  post "vacancy/:id/g_pdf" , to: "vacancies#generate_pdf", as: "vacancy_g_pdf"

  get "admin/job_applications/:id/rate_as_good" , to: "admin/job_applications#rate_as_good", as: "rate_application_good"
  get "admin/job_applications/:id/rate_as_bad" , to: "admin/job_applications#rate_as_bad", as: "rate_application_bad"
  get "admin/job_applications/:id/reject" , to: "admin/job_applications#reject", as: "reject_application"
  get "admin/job_applications/:id/select_moderator" , to: "admin/job_applications#select_moderator", as: "select_moderator"
  get "admin/job_applications/:id/employ" , to: "admin/job_applications#employ", as: "employ"

  

end

app/models/vacancy.rb
class Vacancy < ActiveRecord::Base
  belongs_to :admin
  has_many :job_applications, dependent: :destroy
  #has_many :applicants, through: :job_application
  attr_accessible :description, :location, :requirement, :title, :duties


  validates_presence_of :description, :location, :requirement, :title, :duties, :admin_id
  
  def already_taken_by_user?(user)
    if JobApplication.where(vacancy_id: self.id, user_id: user.id).any?
      true
    else
      false
    end
  end
  
  def display_user_details(user)
    application = user.job_applications.find_by_vacancy_id(self.id)
    salary = application.salary || "You haven't entered a salary"
    application.note = "You haven't entered a note" if application.note.nil? || application.note.empty?
    [salary, application.note, application.id]
  end
end

app/controllers/admin/vacancies_controller.rb
class Admin::VacanciesController < ApplicationController
  before_filter :verify_admin
  # GET /admin/vacancies
  # GET /admin/vacancies.json
  def index
    @vacancies = Vacancy.page(params[:page]).per(30)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @vacancies }
    end
  end

  # GET /vacancies/1
  # GET /vacancies/1.json
  def show
    @vacancy = Vacancy.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @vacancy }
      format.js
    end
  end

  # GET /vacancies/new
  # GET /vacancies/new.json
  def new
    @vacancy = Vacancy.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @vacancy }
      format.js
    end
  end

  # GET /vacancies/1/edit
  def edit
    @vacancy = Vacancy.find(params[:id])
    @vacancy.admin_id = current_user.id
  end

  # POST /vacancies
  # POST /vacancies.json
  def create
    @vacancy = Vacancy.new(params[:vacancy])
    
    if current_user && current_user.admin?
      @vacancy.admin_id = current_user.id
    end
    

    respond_to do |format|
      if @vacancy.save
        format.html { redirect_to [:admin, @vacancy], notice: 'Vacancy was successfully created.' }
        format.json { render json: @vacancy, status: :created, location: @vacancy }
        format.js
      else
        format.html { render action: "new" }
        format.json { render json: @vacancy.errors, status: :unprocessable_entity }
        format.js { render "new" }
      end
    end
  end

  # PUT /vacancies/1
  # PUT /vacancies/1.json
  def update
    @vacancy = Vacancy.find(params[:id])

    respond_to do |format|
      if @vacancy.update_attributes(params[:vacancy])
        format.html { redirect_to [:admin, @vacancy], notice: 'Vacancy was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @vacancy.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vacancies/1
  # DELETE /vacancies/1.json
  def destroy
    @vacancy = Vacancy.find(params[:id])
    @vacancy.destroy

    respond_to do |format|
      format.html { redirect_to admin_vacancies_url, notice: "Vacancy was successfully deleted."  }
      format.json { head :no_content }
      format.js
    end
  end

  def new_pdf
    @vacancy = Vacancy.find(params[:id])
    @footer = PdfFooter.first.footer

    # PDFKit.new takes the HTML and any options for wkhtmltopdf
    # run `wkhtmltopdf --extended-help` for a full list of options
    

    respond_to do |format|
      format.html
      format.pdf {
        kit = PDFKit.new(vacancy_generate_html_for_pdf(@vacancy), :page_size => 'Letter')
        kit.stylesheets << "#{Rails.root}/app/assets/stylesheets/application.css"
        pdf = kit.to_pdf
        send_data(kit.to_pdf, :filename => "#{@vacancy.title}_Vacancy.pdf", :type => 'application/pdf')
      }
    end
  end

  def generate_pdf
    @vacancy = Vacancy.find(params[:id])
    footer = params[:footer]
    object = [@vacancy, footer]


    respond_to do |format|
      format.html
      format.pdf {
        kit = PDFKit.new(vacancy_generate_html_for_pdf(object), :page_size => 'Letter')
        kit.stylesheets << "#{Rails.root}/app/assets/stylesheets/application.css"
        pdf = kit.to_pdf
        send_data(kit.to_pdf, :filename => "#{@vacancy.title}_Vacancy.pdf", :type => 'application/pdf')
      }
    end
  end
end

app/controllers/vacancies_controller.rb
class VacanciesController < ApplicationController
  # before_filter :redirect_admin
  # GET /vacancies
  # GET /vacancies.json
  def index
    @vacancies = Vacancy.page(params[:page]).per(30)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @vacancies }
    end
  end

  # GET /vacancies/1
  # GET /vacancies/1.json
  def show
    @vacancy = Vacancy.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @vacancy }
    end
  end

  # GET /vacancies/new
  # GET /vacancies/new.json
  def new
    @vacancy = Vacancy.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @vacancy }
    end
  end

  # GET /vacancies/1/edit
  def edit
    @vacancy = Vacancy.find(params[:id])
  end

  # POST /vacancies
  # POST /vacancies.json
  def create
    @vacancy = Vacancy.new(params[:vacancy])

    respond_to do |format|
      if @vacancy.save
        format.html { redirect_to @vacancy, notice: 'Vacancy was successfully created.' }
        format.json { render json: @vacancy, status: :created, location: @vacancy }
      else
        format.html { render action: "new" }
        format.json { render json: @vacancy.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /vacancies/1
  # PUT /vacancies/1.json
  def update
    @vacancy = Vacancy.find(params[:id])

    respond_to do |format|
      if @vacancy.update_attributes(params[:vacancy])
        format.html { redirect_to @vacancy, notice: 'Vacancy was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @vacancy.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vacancies/1
  # DELETE /vacancies/1.json
  def destroy
    @vacancy = Vacancy.find(params[:id])
    @vacancy.destroy

    respond_to do |format|
      format.html { redirect_to vacanies_url }
      format.json { head :no_content }
    end
  end

  def new_pdf
    @vacancy = Vacancy.find(params[:id])

    # PDFKit.new takes the HTML and any options for wkhtmltopdf
    # run `wkhtmltopdf --extended-help` for a full list of options
    

    respond_to do |format|
      format.html
      format.pdf {
        kit = PDFKit.new(vacancy_generate_html_for_pdf(@vacancy), :page_size => 'Letter')
        kit.stylesheets << "#{Rails.root}/app/assets/stylesheets/application.css"
        pdf = kit.to_pdf
        send_data(kit.to_pdf, :filename => "#{@vacancy.title}_Vacancy.pdf", :type => 'application/pdf')
      }
    end
  end

  def generate_pdf
    @vacancy = Vacancy.find(params[:id])
    footer = params[:footer]
    object = [@vacancy, footer]


    respond_to do |format|
      format.html
      format.pdf {
        kit = PDFKit.new(vacancy_generate_html_for_pdf(object), :page_size => 'Letter')
        kit.stylesheets << "#{Rails.root}/app/assets/stylesheets/application.css"
        pdf = kit.to_pdf
        send_data(kit.to_pdf, :filename => "#{@vacancy.title}_Vacancy.pdf", :type => 'application/pdf')
      }
    end
  end

  private

  def redirect_admin
    redirect_to admin_vacancies_path if user_signed_in? && current_user.admin?
  end
end

app/helpers/vacancies_helper.rb
module VacanciesHelper
	def can_apply?(user)
		if user == nil
			true
		elsif user.admin? || user.type == "Manager"
			false
		else
			true
		end
	end
end

app/views/admin/vacancies/_a_form.html.slim
div#new_vacancy_container.container
  div.row
    div.col-xs-12.col-sm-12.col-md-10.col-md-offset-1.well.well-sm
      legend.text-center
        | Create Vacancy
        span.close-container.pull-right
          b &times;

      = semantic_form_for([:admin, @vacancy], html: { class: "form-inline"}, remote: true, role: "form") do |f|
        -if @vacancy.errors.any?
          div.alert.alert-danger.alert-dismissable
            button.close type="button" data-dismiss="alert" aria-hidden="true" &times;
            h4
              = pluralize(@vacancy.errors.count, "error")
              | prohibited this vacancy from being saved:

            ul
              - @vacancy.errors.full_messages.each do |msg|
                li= msg
        div.row
          div.col-xs-6.col-md-6
            div.input-group
              span.input-group-addon Title
              = f.text_field :title, class: "form-control", placeholder: "Title"
          div.col-xs-6.col-md-6
            div.input-group
              span.input-group-addon Location
              = f.text_field :location, class: "form-control", placeholder: "Location"
        div.row
          div.col-xs-6.col-md-6
            div.input-group
              span.input-group-addon Requirement
              = f.text_field :requirement, class: "form-control", placeholder: "Requirement"
          div.col-xs-6.col-md-6
            div.input-group
              span.input-group-addon Duties
              = f.text_field :duties, class: "form-control", placeholder: "Duties"
        br
        div.row
          div.col-xs-12.col-md-12
              span.input-group-addon Description
              = f.text_area :description, class: "form-control", placeholder: "Description"
        = f.actions do
          = f.action :submit, as: :button, button_html: { class: "btn btn-primary col-md-offset-4" }

app/views/admin/vacancies/_form.html.slim
= semantic_form_for([:admin, @vacancy], html: { class: "form-horizontal"}) do |f|
  -if @vacancy.errors.any?
    div.alert.alert-danger.alert-dismissable
      button.close type="button" data-dismiss="alert" aria-hidden="true"
      | &times;
      h4
        = pluralize(@vacancy.errors.count, "error")
        | prohibited this vacancy from being saved:

      ul
        - @vacancy.errors.full_messages.each do |msg|
          li= msg

  = f.inputs do
    = f.input :title
    = f.input :location
    = f.input :requirement
    = f.input :duties
    = f.input :description, :input_html => { :class => 'autogrow', :rows => 12, :cols => 40 }

  br

  = f.actions do
    = f.action :submit, as: :button, button_html: { class: "btn btn-primary" }
    - if params[:action] == "edit"
      = link_to [:admin, @vacancy], class: "btn btn-info" do
        | Show #{@vacancy.title} vacancy
    = link_to admin_vacancies_path, class: "btn btn-default" do
      span.icon-arrow-left
      | Back

app/views/admin/vacancies/_vacancy.html.slim
tr.vacancy id="vacancy_#{ vacancy.id}"
  td= vacancy.title
  td= vacancy.location
  td= vacancy.description
  td= vacancy.requirement
  td.text-center.inline
    = link_to "", admin_vacancy_path(vacancy), class: "icon-eye-open eye",              \
                                               title: "Show",                           \
                                               data: { toggle: "tooltip",               \
                                               		 placement: "top" }
    | &nbsp;
    = link_to "", edit_admin_vacancy_path(vacancy), class: "icon-edit edit",            \
                                                    title: "Edit",                      \
                                                    data: { toggle: "tooltip",          \
                                                            placement: "top" }
    | &nbsp;
    = link_to "", admin_vacancy_path(vacancy), class: "icon-trash delete",              \
                                               id: "delete_#{vacancy.title}",           \
                                               title: "Delete",                         \
                                               remote: true,                            \
                                               method: :delete,                         \
                                               data: { toggle: "tooltip",               \
                                                       confirm: "Are you sure?",        \
                                                       placement: "top" }

app/views/admin/vacancies/create.js.erb
function scrollToElement(selector, time, verticalOffset) {
    time = typeof(time) != 'undefined' ? time : 1000;
    verticalOffset = typeof(verticalOffset) != 'undefined' ? verticalOffset : 0;
    element = $(selector);
    offset = element.offset();
    offsetTop = offset.top + verticalOffset;
    $('html, body').animate({
        scrollTop: offsetTop
    }, time);
}

function sleep(milliseconds) {
  var start = new Date().getTime();
  for (var i = 0; i < 1e7; i++) {
    if ((new Date().getTime() - start) > milliseconds){
      break;
    }
  }
}

$(".alert").remove();
$("#new_link_top").show();
$("#new_link_bottom").show();
$(".page-header").after("<div class=\"alert alert-success alert-dismissable\">"
  +" <button type=\"button\" class=\"close\" data-dismiss=\"alert\" aria-hidden=\"true\">&times;</button>Vacancy was successfully created.").slideDown();
scrollToElement("table");
$("#new_vacancy_container").remove();
$( "tr:last" ).after("<%= j render(@vacancy) %>");
scrollToElement("vacancy_#{@vacancy.id}");

app/views/admin/vacancies/destroy.js.erb
$(".alert").remove();
$(".page-header").after("<div class=\"alert alert-success alert-dismissable\"><button type=\"button\" class=\"close\" data-dismiss=\"alert\" aria-hidden=\"true\">&times;</button>Successfully deleted Vacancy.").slideDown();
$('#vacancy_<%= @vacancy.id %>').fadeOut(250);

app/views/admin/vacancies/edit.html.slim
div.row
	= render "admin/sidebar"
	div.col-md-10
		div.page-header
			h1 Editing vacancy
		= render "form"
		br

app/views/admin/vacancies/index.html.slim
div.row
  = render "admin/sidebar"
  div.col-md-10
    div.page-header
      h1 Current vacancies
    - if user_signed_in? && current_user.admin?
      = link_to new_admin_vacancy_path, id: "new_link_top", :class => 'btn btn-primary pull-right icon-plus-sign', remote: true do
        | &nbsp Add Vacancy
    br
    br
    = paginate @vacancies
    table-responsive
      table.table.table-striped.table-bordered.table-hover
        thead
          th.text-center Title
          th.text-center Location
          th.text-center Description
          th.text-center Requirement
          th.text-center Actions
        tbody
          tr
            = content_tag_for(:tr, @vacancies) do |vacancy|
              td= vacancy.title
              td= vacancy.location
              td= vacancy.description
              td= vacancy.requirement
              td.text-center.inline
                = link_to "", admin_vacancy_path(vacancy), class: "icon-eye-open eye",              \
                                                           title: "Show",                           \
                                                           data: { toggle: "tooltip",               \
                                                                   placement: "top" }
                | &nbsp;
                = link_to "", edit_admin_vacancy_path(vacancy), class: "icon-edit edit",            \
                                                                title: "Edit",                      \
                                                                data: { toggle: "tooltip",          \
                                                                        placement: "top" }
                | &nbsp;
                = link_to "", admin_vacancy_path(vacancy), class: "icon-trash delete",              \
                                                           id: "delete_#{vacancy.title}",           \
                                                           title: "Delete",                         \
                                                           remote: true,                            \
                                                           method: :delete,                         \
                                                           data: { toggle: "tooltip",               \
                                                                   confirm: "Are you sure?",        \
                                                                   placement: "top" }
    = link_to new_admin_vacancy_path, id: "new_link_bottom", :class => 'btn btn-primary pull-right icon-plus-sign', remote: true do
      | &nbsp Add Vacancy

app/views/admin/vacancies/new.html.slim
div.row
	= render "admin/sidebar"
	div.col-md-10
		div.page-header
			h1 New vacancy
		= render "a_form"

app/views/admin/vacancies/new.js.erb
function scrollToElement(selector, time, verticalOffset) {
    time = typeof(time) != 'undefined' ? time : 1000;
    verticalOffset = typeof(verticalOffset) != 'undefined' ? verticalOffset : 0;
    element = $(selector);
    offset = element.offset();
    offsetTop = offset.top + verticalOffset;
    $('html, body').animate({
        scrollTop: offsetTop
    }, time);
}

$("#new_vacancy_container").remove();
$("#new_link_top").hide();
$("#new_link_bottom").hide().after('<%= j render "a_form" %>');
$("#vacancy_title").focus();
scrollToElement("#new_vacancy_container");

app/views/admin/vacancies/new_pdf.html.erb
<div class="row">
	<div class="col-md-offset-2 col-md-6">
	<%= image_tag "corporate-logo.png", style: "margin-left: 85%" %>
	<h1><%= @vacancy.title %></h1>
	<hr/>
	<div class="content">
		<p><label><b>Location: </b></label> <%= @vacancy.location %></p><br />
		<p><label><b>Description: </b></label> <%= @vacancy.description %></p><br />
		<p><label><b>Duties: </b></label> <%= @vacancy.duties %></p><br />
		<p><label><b>Requirement: </b></label> <%= @vacancy.requirement %></p><br />
	</div>


<%= form_tag controller: "admin/vacancies", action: "generate_pdf", format: "pdf" do %>
<%= text_area_tag("footer",
	# Initial text
	 @footer,
	 class: "form-control",
	 rows: 10,
	 cols: 20 ) %>
	 <br/>
	 </div>
</div>
<div class="col-md-offset-8">
<%= submit_tag("Generate PDF", class: "btn btn-primary btn-lg") %>
<%= link_to "Back", :back, class: "btn btn-warning btn-lg" %>
<% end %>
</div>

app/views/admin/vacancies/show.html.slim
div.row
  = render "admin/sidebar"
  div.col-md-10
    div.page-header
      h1= @vacancy.title

    dl
      dt Location:
      dd= @vacancy.location

      dt Description:
      dd= @vacancy.description

      dt Duties:
      dd= @vacancy.duties

      dt Requirement:
      dd= @vacancy.requirement

    div.row.col-md-offset-3
      = link_to admin_vacancy_pdf_path(@vacancy), class: "btn btn-lg btn-danger" do
        span.icon-edit
        | Generate PDF
      | &nbsp;
      = link_to "", edit_admin_pdf_footer_path, class: "icon-cog footer",    \
                                                   title: "Change Footer",      \
                                                   style: "font-size: 24px; color: black;", \
                                                    data: { toggle: "tooltip",          \
                                                            placement: "top" }

      br
      br
      = link_to admin_vacancies_path, class: "btn btn-default btn-lg" do
        span.icon-arrow-left
        | Back
      = link_to edit_admin_vacancy_path(@vacancy), class: "btn btn-lg btn-info" do
        span.icon-edit
        | Edit