config/routes.rb
MiniRecruiting::Application.routes.draw do
  root :to => 'vacancies#index'
  
  resources :vacancies, only: :show do
    resources :job_applications, only: [:new, :create]
  end
  
  scope "/applicants/:applicant_id", as: "applicant" do
    resources :job_applications, only: [:edit, :update, :show]
  end
  

  devise_for :users, controllers: {sessions: "sessions"}
  devise_for :applicants, :controllers => {:registrations => "applicant_registrations"}
  devise_for :admin

  resources :job_assignments, only: [:new, :create]
  resources :users
  
  namespace :admin do
    resources :users
    resources :vacancies
    resources :job_applications
    resources :job_assignments, only: :show
    root :to => 'users#index'
    get "vacancies/:id/pdf" , to: "vacancies#new_pdf", as: "vacancy_pdf"
    post "vacancies/:id/g_pdf" , to: "vacancies#generate_pdf", as: "vacancy_g_pdf"
    resources :pdf_footer, only: [:edit, :update]
  end
  get "/guest/apply_for/:vacancy_id/new", to: "guest_apply#new", as: "guest_new"
  post "/guest/apply_for/:vacancy_id/", to: "guest_apply#create", as: "guest_create"
  get "vacancy/:id/pdf" , to: "vacancies#new_pdf", as: "vacancy_pdf"
  post "vacancy/:id/g_pdf" , to: "vacancies#generate_pdf", as: "vacancy_g_pdf"

  get "admin/job_applications/:id/rate_as_good" , to: "admin/job_applications#rate_as_good", as: "rate_application_good"
  get "admin/job_applications/:id/rate_as_bad" , to: "admin/job_applications#rate_as_bad", as: "rate_application_bad"
  get "admin/job_applications/:id/reject" , to: "admin/job_applications#reject", as: "reject_application"
  get "admin/job_applications/:id/select_moderator" , to: "admin/job_applications#select_moderator", as: "select_moderator"
  get "admin/job_applications/:id/employ" , to: "admin/job_applications#employ", as: "employ"

  

end

app/views/admin/_sidebar.html.erb
<% if admin_signed_in? %>
	<div class="col-md-2">
	    <ul class="nav nav-pills nav-stacked admin-list">
	      <li class="<%= 'active' if params[:controller] == 'admin/users' %>"><%= link_to "Users", admin_users_path %></li>
	      <li class="<%= 'active' if params[:controller] == 'admin/vacancies' %>"><%= link_to "Vacancies", admin_vacancies_path %></li>
	      <li class="<%= 'active' if params[:controller] == 'admin/job_applications' %>"><%= link_to "Job Applications", admin_job_applications_path %></li>
	    </ul>
	</div>
<% elsif moderator_signed_in? %>
	<div class="col-md-2">
	    <ul class="nav nav-pills nav-stacked admin-list">
	      <li class="<%= 'active' if params[:controller] == 'admin/job_applications' || params[:controller] == 'admin/job_assignments'%>"><%= link_to "Job Applications", admin_job_applications_path %></li>
	    </ul>
	</div>
<% end %>

app/views/admin/new_pdf.html.erb
<div class="row">
	<%= image_tag "corporate-logo.png", style: "margin-left: 85%" %>
	<h1><%= @vacancy.title %></h1>
	<hr/>
	<div class="content">
		<p><label><b>Location: </b></label> <%= @vacancy.location %></p><br />
		<p><label><b>Description: </b></label> <%= @vacancy.description %></p><br />
		<p><label><b>Duties: </b></label> <%= @vacancy.duties %></p><br />
		<p><label><b>Requirement: </b></label> <%= @vacancy.requirement %></p><br />
	</div>
</div>

<%= form_tag controller: "vacancies", action: "generate_pdf", format: "pdf" do %>
<%= text_area_tag("footer",
	# Initial text
	 "Here's a sample footer. Add your own footer here for the PDF or delete it.",
	 class: "form-control",
	 rows: 10,
	 cols: 20 ) %>
	 <br/>
<%= submit_tag("Generate PDF", class: "btn btn-primary btn-lg") %>
<% end %>