config/routes.rb
MiniRecruiting::Application.routes.draw do
  root :to => 'vacancies#index'
  
  resources :vacancies, only: :show do
    resources :job_applications, only: [:new, :create]
  end
  
  scope "/applicants/:applicant_id", as: "applicant" do
    resources :job_applications, only: [:edit, :update, :show]
  end
  

  devise_for :users, controllers: {sessions: "sessions"}
  devise_for :applicants, :controllers => {:registrations => "applicant_registrations"}
  devise_for :admin

  resources :job_assignments, only: [:new, :create]
  resources :users
  
  namespace :admin do
    resources :users
    resources :vacancies
    resources :job_applications
    resources :job_assignments, only: :show
    root :to => 'users#index'
    get "vacancies/:id/pdf" , to: "vacancies#new_pdf", as: "vacancy_pdf"
    post "vacancies/:id/g_pdf" , to: "vacancies#generate_pdf", as: "vacancy_g_pdf"
    resources :pdf_footer, only: [:edit, :update]
  end
  get "/guest/apply_for/:vacancy_id/new", to: "guest_apply#new", as: "guest_new"
  post "/guest/apply_for/:vacancy_id/", to: "guest_apply#create", as: "guest_create"
  get "vacancy/:id/pdf" , to: "vacancies#new_pdf", as: "vacancy_pdf"
  post "vacancy/:id/g_pdf" , to: "vacancies#generate_pdf", as: "vacancy_g_pdf"

  get "admin/job_applications/:id/rate_as_good" , to: "admin/job_applications#rate_as_good", as: "rate_application_good"
  get "admin/job_applications/:id/rate_as_bad" , to: "admin/job_applications#rate_as_bad", as: "rate_application_bad"
  get "admin/job_applications/:id/reject" , to: "admin/job_applications#reject", as: "reject_application"
  get "admin/job_applications/:id/select_moderator" , to: "admin/job_applications#select_moderator", as: "select_moderator"
  get "admin/job_applications/:id/employ" , to: "admin/job_applications#employ", as: "employ"

  

end

app/models/job_application.rb
class JobApplication < ActiveRecord::Base
  attr_accessible :vacancy_id, :user_id, :note, :salary

  alias_attribute :applicant_id, :user_id
  
  validates_presence_of :vacancy_id, :applicant_id
  validates :user_id, :uniqueness => {:scope => :vacancy_id}
  
  belongs_to :user
  belongs_to :vacancy
  has_many :job_assignments, dependent: :destroy
  has_many :moderators, through: :job_assignments

  state_machine :initial => :send do

  	event :reject do
  		transition :send => :rejected
  		transition :manager_review_listed => :rejected
  	end

  	event :forward_to_manager do
  		transition :send => :manager_review
  	end

  	event :mark_as_good do
  		transition :manager_review => :manager_review_listed
  	end

  	event :mark_as_bad do
  		transition :manager_review => :manager_review_listed
  	end

  	event :employ do
  		transition :manager_review_listed => :employed
  	end
  end

  def self.find_by_state(state)
  	self.where(state: state)
  end
end

app/controllers/admin/job_applications_controller.rb
class Admin::JobApplicationsController < ApplicationController
  before_filter :verify_admin, except: [:index, :show, :rate_as_good, :rate_as_bad]
  before_filter :verify_mod_privilges
  # GET /job_applications
  # GET /job_applications.json
  def index
    if current_user.admin?
      @new = JobApplication.where(state: @state)
      @vacancies = Vacancy.all
    else
      @job_assignments = JobAssignment.where(manager_id: current_user.id, reviewed: false)
    end

    respond_to do |format|
      format.html # show.html.erb
      format.js
    end
  end

  # GET /job_applications/1
  # GET /job_applications/1.json
  def show
    @vacancy = Vacancy.find(params[:id])
    @new = JobApplication.where(state: "send", vacancy_id: @vacancy.id).includes(:user)
    @forwarded = JobApplication.where(state: "manager_review", vacancy_id: @vacancy.id).includes(:user)
    @reviewed = JobApplication.where(state: "manager_review_listed", vacancy_id: @vacancy.id).includes(:user)
    @employed = JobApplication.where(state: "employed", vacancy_id: @vacancy.id).includes(:user)
    @rejected = JobApplication.where(state: "rejected", vacancy_id: @vacancy.id).includes(:user)

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @job_application }
    end
  end

  # GET /job_applications/new
  # GET /job_applications/new.json
  def new
    @vacancy = Vacancy.find_by_id(params[:vacancy_id])
    @job_application = JobApplication.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @job_application }
    end
  end

  # GET /job_applications/1/edit
  def edit
    @job_application = JobApplication.find(params[:id])
  end

  # POST /job_applications
  # POST /job_applications.json
  def create
    @job_application = JobApplication.new(params[:job_application])
    @vacancy = Vacancy.find_by_id(params[:vacancy_id]);
    if user_signed_in? && !current_user.admin?
      applicant = Applicant.find_by_id(current_user.id)
      @job_application.applicant_id = current_user.id
      @job_application.vacancy_id = @vacancy.id
    end
    
    respond_to do |format|
      if @job_application.save
        format.html { redirect_to @vacancy, notice: 'Job application was successfully created.' }
        format.json { render json: @job_application, status: :created, location: [applicant, @job_application] }
      else
        format.html { render action: "new" }
        format.json { render json: @job_application.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /job_applications/1
  # PUT /job_applications/1.json
  def update
    @job_application = JobApplication.find(params[:id])

    respond_to do |format|
      if @job_application.update_attributes(params[:job_application])
        format.html { redirect_to vacancy_path(@job_application.vacancy_id), notice: 'Job application was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @job_application.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /job_applications/1
  # DELETE /job_applications/1.json
  def destroy
    @job_application = JobApplication.find(params[:id])
    @job_application.destroy

    respond_to do |format|
      format.html { redirect_to job_applications_url }
      format.json { head :no_content }
    end
  end

  def rate_as_good
    @job_application = JobApplication.find(params[:id])
    vacancy = @job_application.vacancy
    @job_application.mark_as_good
    assignment = JobAssignment.find_by_job_application_id(@job_application.id)
    assignment.reviewed = true
    assignment.save
    ApplicationNotifier.reviewed_application(current_user, vacancy, @job_application.user).deliver


    redirect_to admin_job_applications_path, notice: "Reviewed the application from #{@job_application.user.fullname} for #{@job_application.vacancy.title} as good"
  end

  def rate_as_bad
    @job_application = JobApplication.find(params[:id])
    vacancy = @job_application.vacancy
    @job_application.mark_as_bad
    assignment = JobAssignment.find_by_job_application_id(@job_application.id)
    assignment.reviewed = true
    assignment.save
    ApplicationNotifier.bad_reviewed_application(current_user, vacancy, @job_application.user).deliver

    redirect_to admin_job_applications_path , notice: "Reviewed the application from #{@job_application.user.fullname} for #{@job_application.vacancy.title} as bad"
  end

  def reject
    @job_application = JobApplication.find(params[:id])
    vacancy = @job_application.vacancy
    @state = @job_application.state
    @job_application.reject
    @job_application.save!
    ApplicationNotifier.rejected_application(vacancy, @job_application.user).deliver

    respond_to do |format|
      format.html {redirect_to admin_job_application_path(vacancy.id), notice: "Rejected the application from #{@job_application.user.fullname} for #{@job_application.vacancy.title}"}
      format.js
    end
  end

  def employ
    @job_application = JobApplication.find(params[:id])
    vacancy = @job_application.vacancy
    @job_application.employ
    @job_application.save!
    ApplicationNotifier.accepted_application(vacancy, @job_application.user).deliver
    # ApplicationNotifier.accepted_application_moderator(vacancy, @job_application.user).deliver
    
    respond_to do |format|
      format.html { redirect_to admin_job_application_path(vacancy.id), notice: "Employed #{@job_application.user.fullname} for #{@job_application.vacancy.title}" }
      format.js
    end
  end

  def select_moderator
    @job_application = JobApplication.find(params[:id])
    @assignment = JobAssignment.new()

    respond_to do |format|
      format.html
      format.js
    end
  end
end

app/controllers/job_applications_controller.rb
class JobApplicationsController < ApplicationController
  # GET /job_applications
  # GET /job_applications.json
  def index
    @job_applications = JobApplication.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @job_applications }
    end
  end

  # GET /job_applications/1
  # GET /job_applications/1.json
  def show
    @job_application = JobApplication.find(params[:id])
    @vacancy = Vacancy.find_by_id(@job_application.vacancy_id)

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @job_application }
    end
  end

  # GET /job_applications/new
  # GET /job_applications/new.json
  def new
    @vacancy = Vacancy.find_by_id(params[:vacancy_id]);
    @job_application = JobApplication.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @job_application }
    end
  end

  # GET /job_applications/1/edit
  def edit
    @job_application = JobApplication.find(params[:id])
  end

  # POST /job_applications
  # POST /job_applications.json
  def create
    @job_application = JobApplication.new(params[:job_application])
    @vacancy = Vacancy.find_by_id(params[:vacancy_id]);
    if user_signed_in? && !current_user.admin?
      applicant = Applicant.find_by_id(current_user.id)
      @job_application.applicant_id = current_user.id
      @job_application.vacancy_id = @vacancy.id
    end
    
    respond_to do |format|
      if @job_application.save
        ApplicationNotifier.new_application(@vacancy, current_user).deliver
        format.html { redirect_to @vacancy, notice: 'Job application was successfully created.' }
        format.json { render json: @job_application, status: :created, location: [applicant, @job_application] }
      else
        format.html { render action: "new" }
        format.json { render json: @job_application.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /job_applications/1
  # PUT /job_applications/1.json
  def update
    @job_application = JobApplication.find(params[:id])

    respond_to do |format|
      if @job_application.update_attributes(params[:job_application])
        format.html { redirect_to vacancy_path(@job_application.vacancy_id), notice: 'Job application was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @job_application.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /job_applications/1
  # DELETE /job_applications/1.json
  def destroy
    @job_application = JobApplication.find(params[:id])
    @job_application.destroy

    respond_to do |format|
      format.html { redirect_to job_applications_url }
      format.json { head :no_content }
    end
  end

  
end

app/helpers/job_applications_helper.rb
module JobApplicationsHelper
	def reviewed_by?(job_application)
		if JobAssignment.find_by_job_application_id(job_application.id)
			JobAssignment.find_by_job_application_id(job_application.id).manager.fullname
		else
			"Not assigned."
		end 
	end

	def send?(application)
		application.state == "send"
	end

	def forwarded?(application)
		application.state == "manager_review"
	end

	def reviewed?(application)
		application.state == "manager_review_listed"
	end
end

app/views/admin/job_applications/_accordion_content.html.erb
  <% tab.each_with_index do |job_application, index| %>
  <div class="panel panel-default" id="user_<%= job_application.user.id%>">
    <div class="panel-heading text-center">
      <h4 class="panel-title">
        <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion_<%= tab.object_id %>" href="#collapse<%= "#{job_application.state}#{index}" %>">
          <%= job_application.user.fullname %>
        </a>
      </h4>
    </div>
    <div id="collapse<%= "#{job_application.state}#{index}" %>" class="panel-collapse collapse">
      <div class="panel-body">
        <dl class="dl-horizontal">
          <dt>Firstname:</dt>
          <dd><%= link_to job_application.user.firstname, admin_user_path(job_application.user), style: "text-decoration: underline;" %></dd>

          <dt>Lastname:</dt>
          <dd><%= job_application.user.lastname %></dd>

          <dt>Email:</dt>
          <dd><%= job_application.user.email %></dd>

          <dt>Applied at:</dt>
          <dd><%= i18n_date(job_application.created_at) %></dd>

          <dt>Offered salary:</dt>
          <dd><%= job_application.salary %></dd>

          <dt>Note by applicant:</dt>
          <dd><%= job_application.note %></dd>

          <% if !current_user.admin? %>
          <% else %>
            <% if send?(job_application) %>
              <div class="pull-right new-option">
                <%= link_to "Forward", select_moderator_path(job_application), class: "icon-tags", remote: true %>
                <%= link_to "Reject", reject_application_path(job_application), class: "icon-trash", id: "reject_#{job_application.id}", remote: true,
                                                                                data: { confirm: "Reject this Applicant?" } %>
              </div>
            <% elsif forwarded?(job_application) %>
              <div class="pull-right new-option">
                <h3>Reviewed by</h3>
                <p><%= reviewed_by?(job_application) %></p>
              </div>
            <% elsif reviewed?(job_application) %>
              <div class="pull-right new-option">
                <h3>Reviewed by</h3>
                <p><%= reviewed_by?(job_application) %></p>
                <br />
                <%= link_to "Employ", employ_path(job_application), class: "icon-check", id: "employ_#{job_application.id}", remote: true,
                                                                                data: { confirm: "Employ this Applicant?" }  %>
                <%= link_to "Reject", reject_application_path(job_application), class: "icon-trash", id: "reject_#{job_application.id}", remote: true,
                                                                                data: { confirm: "Reject this Applicant?" } %>
              </div>
            <% end %>
          <% end %>
        </dl>
      </div>
    </div>
  </div>

  <% end %>

app/views/admin/job_applications/_edit_form.html.erb
<%= semantic_form_for([:applicant, @job_application], :html => { :class => "form-horizontal" }) do |f| %>
  <% if @job_application.errors.any? %>
    <div class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <h4><%= pluralize(@job_application.errors.count, "error") %> prohibited this job_application from being saved:</h4>

      <ul>
      <% @job_application.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.inputs :name => "Your details" do %>
      <%= f.input :salary, :input_html => { :style => "height: 25px"} %>
      <%= f.input :note, :input_html => { :class => 'autogrow', :rows => 6, :cols => 20 } %>
  <% end %>
  

  <%= f.actions do %>
      <%= f.action :submit, :as => :button %>
  <% end %>
<% end %>

app/views/admin/job_applications/_form.html.erb
<%= semantic_form_for([:vacancy, @job_application], :html => { :class => "form-horizontal" }) do |f| %>
  <% if @job_application.errors.any? %>
    <div class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <h4><%= pluralize(@job_application.errors.count, "error") %> prohibited this job_application from being saved:</h4>

      <ul>
      <% @job_application.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.inputs :name => "Your details" do %>
      <%= f.input :salary, :input_html => { :style => "height: 25px"} %>
      <%= f.input :note, :input_html => { :class => 'autogrow', :rows => 6, :cols => 20 } %>
  <% end %>
  

  <%= f.actions do %>
      <%= f.action :submit, :as => :button %>
  <% end %>
<% end %>

app/views/admin/job_applications/_moderator_index.html.haml
.col-md-10
  .page-header
    %h1 Job Applications to review
  - if @job_assignments.any?
    .table-responsive
      %table.table.table-striped.table-bordered.table-hover
        %thead
          %tr
            %th Vacancy
            %th Applicant
        %tbody
          = content_tag_for(:tr, @job_assignments, class: "hover") do |assignment|
            %td= link_to assignment.job_application.vacancy.title, admin_job_assignment_path(assignment)
            %td.text-center= link_to assignment.job_application.user.fullname, admin_job_application_path(assignment.job_application.vacancy)
  - else
    %p There are currently no assignments to review.

app/views/admin/job_applications/_moderator_show.html.erb
<div class="row">
  <%= render "admin/sidebar" %>
  <div class="col-md-10">
    <div class="page-header">
      <h1>All Applications for <%= @vacancy.title %></h1>
    </div>
    <!-- <div id="tabs">
      <ul>
        <li><a href="#tabs-2">Applications to review</a></li>
      </ul>
      <div id="tabs-2">
        <% if @forwarded.any? %>
        <%= render :partial => "accordion_content", :locals => { :tab => @forwarded } %>
        <% else %>
        <h4>There are currently no applications to review.</h4>
        <% end %>
      </div>
    </div> -->

    <br />
    <%= link_to :back, class: "text-center btn btn-lg btn-info back col-md-offset-1"  do %>
    <span class="icon-arrow-left"></span>
    Back
    <% end %>
  </div>
</div>

app/views/admin/job_applications/_select_moderator.html.erb
<div class="row select-manager">
	<div class="pull-right col-md-4 well">
		<span class="close-container pull-right"><b>&times;</b></span>
		<%= semantic_form_for(@assignment, remote: true) do |f| %>
			<%= f.inputs do %>
				<div class="input-group">
					<%= f.input :manager, :include_blank => false, input_html: { class: "form-control" } %>
				</div>
				<%= f.input :job_application, as: :hidden, input_html: { value: @job_application.id } %>
			<% end %>
			<br />
			<%= f.actions do %>
				<%= f.action :submit, as: :button, label: "Forward to manager", button_html: { class: "btn btn-info btn-sm pull-right" } %>
			<% end %>
		<% end %>
	</div>
</div>

app/views/admin/job_applications/_tabs.html.erb
<li>
	<a href="#tabs-<%= index %>">
	<span class="badge pull-right" id="tab_<%= index %>"><%= state.count %></span>
		<%= text %>
	</a>
</li>

app/views/admin/job_applications/edit.html.erb
<div class="page-header">
  <h1>Editing job_application</h1>
</div>

<%= render 'edit_form' %>

app/views/admin/job_applications/employ.js.erb
$(".alert").remove();
$(".page-header").after("<div class=\"alert alert-success alert-dismissable\"><button type=\"button\" class=\"close\" data-dismiss=\"alert\" aria-hidden=\"true\">&times;</button>Employed <%= @job_application.user.fullname %> for <%=@job_application.vacancy.title %>").slideDown();
var employed = "#h_employed"
if ($(employed)) {
	$(employed).remove();
}

var user = $("#user_<%= @job_application.user.id %>");
user.appendTo($(".accordion_employed"));
var object_id = $(".accordion_employed").attr('id');
user.find("a").attr("data-parent", object_id)
user.find($(".new-option")).remove();
user.collapse();

<%# Decrements the amount of the Reviewed Tab%>
var amount_first_tab = parseInt($("#tab_3").text());
amount_first_tab--;
$("#tab_3").text(amount_first_tab);

<%# Increments the amount of the Employed Tab%>
var amount_new_tab = parseInt($("#tab_4").text());
amount_new_tab++;
$("#tab_4").text(amount_new_tab);

if (amount_first_tab == 0) {
	$(".accordion_reviewed").append("<h4 id=\"h_reviewed\">There are no reviewed applications.</h4>");
}

app/views/admin/job_applications/index.html.haml
.row
	= render "admin/sidebar"
	- if current_user.admin?
		= render "admin/job_applications/admin_index"
	- else
		= render "admin/job_applications/moderator_index"

app/views/admin/job_applications/new.html.erb
<div class="page-header">
  <h1>Application for <%= @vacancy.title %></h1>
</div>

<%= render 'form' %>

app/views/admin/job_applications/select_moderator.html.erb
<div class="row">
	<%= render "admin/sidebar" %>
	<div class="col-md-10">
		<div class="page-header">
			<h3>Select Manager</h3>
		</div>
		<%= semantic_form_for(@assignment) do |f| %>
			<%= f.inputs do %>
				<div class="input-group">
					<%= f.input :manager, :include_blank => false, input_html: { class: "form-control" } %>
				</div>
				<%= f.input :job_application, as: :hidden, input_html: { value: @job_application.id } %>
			<% end %>
			<br />
			<%= f.actions do %>
				<%= f.action :submit, as: :button, label: "Forward to manager", button_html: { class: "btn btn-info" } %>
				<%= link_to "Back", :back, class: "btn btn-warning" %>
			<% end %>
		<% end %>
	</div>
</div>

app/views/admin/job_applications/select_moderator.js.erb
$(".select-manager").remove();

$("#user_<%= @job_application.user.id %> .new-option").after("<%= j render 'select_moderator' %>");

$("#user_<%= @job_application.user.id %> .new-option").hide();

$(".close-container").on("click", function() {
	$(".select-manager").remove();
	$("#user_<%= @job_application.user.id %> .new-option").show();
});

app/views/admin/job_applications/show.html.erb
<% if admin_signed_in? %>
  <%= render "admin/job_applications/admin_show" %>
<% elsif moderator_signed_in? %>
  <%= render "admin/job_applications/moderator_show" %>
<% end %>