config/routes.rb
MiniRecruiting::Application.routes.draw do
  root :to => 'vacancies#index'
  
  resources :vacancies, only: :show do
    resources :job_applications, only: [:new, :create]
  end
  
  scope "/applicants/:applicant_id", as: "applicant" do
    resources :job_applications, only: [:edit, :update, :show]
  end
  

  devise_for :users, controllers: {sessions: "sessions"}
  devise_for :applicants, :controllers => {:registrations => "applicant_registrations"}
  devise_for :admin

  resources :job_assignments, only: [:new, :create]
  resources :users
  
  namespace :admin do
    resources :users
    resources :vacancies
    resources :job_applications
    resources :job_assignments, only: :show
    root :to => 'users#index'
    get "vacancies/:id/pdf" , to: "vacancies#new_pdf", as: "vacancy_pdf"
    post "vacancies/:id/g_pdf" , to: "vacancies#generate_pdf", as: "vacancy_g_pdf"
    resources :pdf_footer, only: [:edit, :update]
  end
  get "/guest/apply_for/:vacancy_id/new", to: "guest_apply#new", as: "guest_new"
  post "/guest/apply_for/:vacancy_id/", to: "guest_apply#create", as: "guest_create"
  get "vacancy/:id/pdf" , to: "vacancies#new_pdf", as: "vacancy_pdf"
  post "vacancy/:id/g_pdf" , to: "vacancies#generate_pdf", as: "vacancy_g_pdf"

  get "admin/job_applications/:id/rate_as_good" , to: "admin/job_applications#rate_as_good", as: "rate_application_good"
  get "admin/job_applications/:id/rate_as_bad" , to: "admin/job_applications#rate_as_bad", as: "rate_application_bad"
  get "admin/job_applications/:id/reject" , to: "admin/job_applications#reject", as: "reject_application"
  get "admin/job_applications/:id/select_moderator" , to: "admin/job_applications#select_moderator", as: "select_moderator"
  get "admin/job_applications/:id/employ" , to: "admin/job_applications#employ", as: "employ"

  

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :job_applications, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  attr_accessible :firstname, :lastname
  
  validates_presence_of :firstname, :lastname
  
  def fullname
    "#{firstname} #{lastname}"
  end

  def admin?
    false
  end

  def to_s
    self.fullname
  end

private
  def mass_assignment_authorizer(role = :default)
      super + [:type]
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_filter :verify_admin
  # GET /users
  # GET /users.json
  def index
    sort_order = ["Admin", "Moderator", "Applicant"]
    @users = User.order("type asc").page(params[:page]).per(30)


    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
      format.js
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to admin_root_path, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
        format.js
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
        format.js { render "new"}
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])
    @user.firstname = params[:user][:firstname]
    @user.lastname = params[:user][:lastname]
    @user.email = params[:user][:email]

    respond_to do |format|
      if params[:user][:password] == ""
        if @user.save(validation: false)
          format.html { redirect_to [:admin, @user], notice: 'User was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render action: "edit" }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      else
        @user.password = params[:user][:password]
        @user.password_confirmation = params[:user][:password]
        if @user.save
          format.html { redirect_to [:admin, @user], notice: 'User was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render action: "edit" }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end          
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to admin_root_path }
      format.json { head :no_content }
      format.js
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
    authorize! :read, @user

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_admin.html.erb
<div class="row-fluid">
  <div class="span4">
    <br/>
    <ul class="list-group">
      <li class="list-group-item">Test</li>
      <li class="list-group-item">Test</li>
      <li class="list-group-item">Test</li>
    </ul>
  </div>
  <div class="span8">
    <%= yield %>
  </div>
</div>

app/views/admin/users/_form.html.haml
= semantic_form_for([:admin, @user], html: { class: "form-horizontal"}) do |f|
  - if @user.errors.any?
    .alert.alert-danger.alert-dismissable
      %button.close{type: "button", "data-dismiss" => "alert", "aria-hidden" => "true"} &times;
      %h4 #{pluralize(@users.errors.count, "error")} prohibited this user from being saved:

      %ul
        - @user.errors.full_messages.each do |msg|
          %li= msg

  = f.inputs name: "Personal" do
    = f.input :firstname, html: {class: "form-control"}
    = f.input :lastname
    = f.input :email
  / = f.input :type, as: :radio, collection: ["Admin", "Manager", "Applicant"], include_blank: false

  = f.inputs name: "Security" do
    = f.input :password, label: "New Password", required: false

  %br

  = f.action :submit, button_html: { class: "btn btn-primary"}

app/views/admin/users/_new_user.html.erb
<div class="container" id="new_user_container">
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-10 col-md-offset-1 well well-sm">
            <legend class="text-center">Create user<span class="close-container pull-right"><b>&times;</b></span></legend>
            <%= semantic_form_for([:admin, @user], html: { class: "form-horizontal"}, remote: true) do |f| %>
            	<% if @user.errors.any? %>
	            	<div class="alert alert-danger alert-dismissable">
						<button class="close" type="button" data-dismiss="alert" aria-hidden="true">&times;</button>
						<h4><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h4>
						<ul>
							<% @user.errors.full_messages.each do |msg| %>
							<li><%= msg %></li>
							<% end %>
						</ul>
					</div>
				<% end %>

	            <div class="row">
	                <div class="col-xs-6 col-md-6">
		                <div class="input-group">
		                	<span class="input-group-addon">Firstname</span>
		                	<%= f.text_field :firstname, focus: true, placeholder: "Firstname", class: "form-control" %>
		                </div>
	                </div>
	                <div class="col-xs-6 col-md-6">
	                	<div class="input-group">
		                	<span class="input-group-addon">Lastname</span>
	                    	<%= f.text_field :lastname, required: true, placeholder: "Lastname", class: "form-control" %>
	                    </div>
	                </div>
	            </div>
	            <div class="row">
		            <div class="col-xs-6 col-md-6">
		            	<div class="input-group">
		                	<span class="input-group-addon">Email</span>
		            		<%= f.email_field :email, required: true, placeholder: "Email Address", class: "form-control" %>
		            	</div>
		            </div>
		            <div class="col-xs-6 col-md-6">
		            	<div class="input-group">
		                	<span class="input-group-addon">Role</span>
		            		<%= f.select :type, ["Admin", "Manager", "Applicant"], {},  {class: "form-control"} %>
		            	</div>
		            </div>
		        </div>
	            <div class="row">
		            <div class="col-xs-6 col-md-6">
		            	<div class="input-group">
		                	<span class="input-group-addon">Password</span>
							<%= f.password_field :password, required: true, placeholder: "Password", class: "form-control" %>
						</div>
		            </div>
		            <div class="col-xs-6 col-md-6">
		            	<div class="input-group">
		                	<span class="input-group-addon">Password Confirmation</span>
		            		<%= f.password_field :password_confirmation, required: true, placeholder: "Password Confirmation", class: "form-control" %>
		            	</div>
		            </div>
	            </div>
	            
	            
	            <br />
	            <div class="col-md-offset-3 col-md-6">
		            <%= f.submit "Create User", class: "btn btn-lg btn-primary btn-block" %>
	            </div>
            <% end %>
        </div>
    </div>
</div>

app/views/admin/users/_user.html.haml
%tr.user{class: "#{user.type}",id: "user_#{user.id}"}
  %td= user.firstname
  %td= user.lastname
  %td= user.email
  %td= user.type
  %td.text-center
    = link_to "", admin_user_path(user), class: "icon-eye-open eye",         |
                                         id: user.email,                     |
                                         title: "Show",                      |
                                         data: {toggle: "tooltip",           |
                                                placement: "top"}

    = link_to "", edit_admin_user_path(user), class: "icon-edit edit",      |
                                              title: "Edit",                |
                                              data: { toggle: "tooltip",    |
                                                      placement: "top"}
    - unless user.admin?
      = link_to "", [:admin, user], class: "icon-trash delete",             |
                                    id: "delete_#{user.email}",             |
                                    title: "Delete",                        |
                                    remote: :true,                          |
                                    method: :delete,                        |
                                    data: { confirm:   "Are you sure?",     |
                                            toggle:    "tooltip",           |
                                            placement: "top" }

app/views/admin/users/create.js.erb
$(".alert").remove();
$("#new_user_container").remove();
$("#new_user_top").show();
$("#new_user_bottom").show();

$(".page-header").after("<div class=\"alert alert-success alert-dismissable\">"
	+" <button type=\"button\" class=\"close\" data-dismiss=\"alert\" aria-hidden=\"true\">&times;</button><%= @user.type %> was successfully created.").slideDown();

<% if User.where(type: @user.type).count > 1 %>
$(".<%= @user.type %>:last").after("<%= j render(@user) %>");

<% elsif @user.type == "Applicant" %>
$(".Admin:last").after("<%= j render(@user) %>");

<% elsif @user.type == "Manager" %>
	<% if User.where(type: "Applicant").any? %>
	$(".Applicant:last").after("<%= j render(@user) %>");
	<% else %>
	$(".Admin:last").after("<%= j render(@user) %>");
	<% end %>
<% end %>

app/views/admin/users/destroy.js.erb
$(".alert").remove();
$(".page-header").after("<div class=\"alert alert-success alert-dismissable\"><button type=\"button\" class=\"close\" data-dismiss=\"alert\" aria-hidden=\"true\">&times;</button>Successfully deleted <%= @user.fullname %>.").slideDown();
$('#user_<%= @user.id %>').fadeOut(250);

app/views/admin/users/edit.html.haml
.row
  = render "admin/sidebar"
  .col-md-10
    .page-header
      %h1 Edit
      = @user.fullname
    = render "form"
    %br
    .row.col-md-offset-4
      = link_to admin_root_path, class: "btn btn-default btn-lg" do
        %span.icon-arrow-left
        Back
      = link_to [:admin, @user], class: "btn btn-lg btn-info" do
        %span.icon-eye-open
        Show

app/views/admin/users/index.html.haml
.row
  = render "admin/sidebar"
  .col-md-10
    
    .page-header
      %h1 Listing Users
    = link_to new_admin_user_path, id: "new_user_top",:class => 'btn btn-primary pull-right icon-plus-sign', remote: true do
      &nbsp; Add User
    %br
    %br
    
    = paginate @users
    .table-responsive
      %table.table.table-striped.table-bordered.table-hover
        %thead
          %tr
            %th.text-center Firstname
            %th.text-center Lastname
            %th.text-center Email
            %th.text-center Type
            %th.text-center Actions
        %tbody
          - @users.each do |user|
            %tr{class: user.type, id: "user_#{user.id}"}
              %td= user.firstname
              %td= user.lastname
              %td= user.email
              %td= user.type
              %td.text-center
                = link_to "", admin_user_path(user), class: "icon-eye-open eye",         |
                                                     id: user.email,                     |
                                                     title: "Show",                      |
                                                     data: {toggle: "tooltip",           |
                                                            placement: "top"}
                -if current_user == user
                  = link_to "", edit_user_registration_path, class: "icon-edit edit",      |
                                                            title: "Edit",                |
                                                            data: { toggle: "tooltip",    |
                                                                    placement: "top"}
                -else
                  = link_to "", edit_admin_user_path(user), class: "icon-edit edit",      |
                                                            title: "Edit",                |
                                                            data: { toggle: "tooltip",    |
                                                                    placement: "top"}

                - unless user.admin?
                  = link_to "", [:admin, user], class: "icon-trash delete",             |
                                                id: "delete_#{user.email}",             |
                                                title: "Delete",                        |
                                                remote: :true,                          |
                                                method: :delete,                        |
                                                data: { confirm:   "Are you sure?",     |
                                                        toggle:    "tooltip",           |
                                                        placement: "top" }
    = link_to new_admin_user_path, id: "new_user_bottom",:class => 'btn btn-primary pull-right icon-plus-sign', remote: true do
      &nbsp; Add User

app/views/admin/users/new.html.erb
<h1>New user</h1>

<%= render 'new_user' %>

<%= link_to 'Back', admin_users_path %>

app/views/admin/users/new.js.erb
function scrollToElement(selector, time, verticalOffset) {
    time = typeof(time) != 'undefined' ? time : 1000;
    verticalOffset = typeof(verticalOffset) != 'undefined' ? verticalOffset : 0;
    element = $(selector);
    offset = element.offset();
    offsetTop = offset.top + verticalOffset;
    $('html, body').animate({
        scrollTop: offsetTop
    }, time);
}

$("#new_user_container").remove();
$("#new_user_top").hide();
$("#new_user_bottom").hide();
$("table").after('<%= j render "new_user" %>');
$("#user_firstname").focus();

scrollToElement("#new_user_container");

app/views/admin/users/show.html.haml
.row
  = render "admin/sidebar"
  .col-md-10
    .row
      .page-header
        %h1= @user.fullname
      .col-md-6
        %h2 Details
        %p
          %b Firstname:
          = @user.firstname

        %p
          %b Lastname:
          = @user.lastname

        %p
          %b Email:
          = @user.email
      .col-md-6
        - if !@user.admin? && @user.job_applications.any?
          %h2 Applicant for:
          %ul.list-group
            - @user.job_applications.each do |jAp|
              %li.list-group-item= link_to jAp.vacancy.title, jAp.vacancy
      %br
      .row.col-md-offset-4
        = link_to admin_root_path, class: "btn btn-default btn-lg" do
          %span.icon-arrow-left
          Back

        = link_to edit_admin_user_path(@user), class: "btn btn-primary btn-lg" do
          %span.icon-edit
          Edit